name: Deploy to PyPI

on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Set up Rye
        uses: eifinger/setup-rye@v2
        with:
          enable-cache: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync with Rye
        run: rye sync

      - name: Build distribution packages
        run: rye build --clean

      # - name: Publish to PyPI
      #   run: rye publish --yes --verbose --token ${{ secrets.PYPI_TOKEN }}
